class Test:
	def testLegs(self):
		legs = Legs()
		powerSupply.displayPowerRemaining()
		legs.run(powerSupply)
		powerSupply.displayPowerRemaining()
		legs.walk(powerSupply)
		powerSupply.displayPowerRemaining()
		legs.roundHouse(powerSupply)
		powerSupply.displayPowerRemaining()
	def testArms(self):
		arms = Arms()
		powerSupply.displayPowerRemaining()
		arms.punch(powerSupply)
		powerSupply.displayPowerRemaining()
		arms.shoot(powerSupply)
		powerSupply.displayPowerRemaining()
		arms.handcuff(powerSupply)
		powerSupply.displayPowerRemaining()
	def testVision(self):
		vision = Vision()
		powerSupply.displayPowerRemaining()
		vision.identifyCriminal(powerSupply)
		powerSupply.displayPowerRemaining()
		vision.targetCriminal(powerSupply)
	def testSpeech(self):
		speech = Speech()
		powerSupply.displayPowerRemaining()
		speech.yellHalt(powerSupply)
		powerSupply.displayPowerRemaining()
		speech.readRights(powerSupply)
		powerSupply.displayPowerRemaining()
		speech.mutterNoises(powerSupply)
		powerSupply.displayPowerRemaining()